environment:
  matrix:
    - RUBY_VERSION: "25-x64"

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v
  - bundle exec rake vendor:windows

test_script:
  - bundle exec ruby test/onnxruntime_test.rb --name test_session_options
